server:
  port: 9002

spring:
  application:
    name: novel-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 500
        readTimeout: 500
